using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace MVA_poe
{
    /// <summary>
    /// Interaction logic for Auth.xaml
    /// </summary>
    public partial class Auth : Window
    {
        // Constructor for the Auth class
        public Auth()
        {
            // Initialize the component (generated by XAML)
            InitializeComponent();

            // Navigate to the Register page
            fContainer.Navigate(new System.Uri("Pages/Register.xaml", UriKind.RelativeOrAbsolute));
        }

        //----------------------------------------------------------------------------//

        // Event handler for the Register button click event
        private void btnRegister_Click(object sender, RoutedEventArgs e)
        {
            // Navigate to the Register page
            fContainer.Navigate(new System.Uri("Pages/Register.xaml", UriKind.RelativeOrAbsolute));
        }

        //----------------------------------------------------------------------------//

        // Event handler for the Login button click event
        private void btnLogin_Click(object sender, RoutedEventArgs e)
        {
            // Navigate to the Login page
            fContainer.Navigate(new System.Uri("Pages/Login.xaml", UriKind.RelativeOrAbsolute));
        }

        //----------------------------------------------------------------------------//

        // Start: Button Close | Restore | Minimize 

        // Event handler for the Close button click event
        private void btnClose_Click(object sender, RoutedEventArgs e)
        {
            // Close the window
            Close();
        }

        //----------------------------------------------------------------------------//

        // Event handler for the Restore button click event
        private void btnRestore_Click(object sender, RoutedEventArgs e)
        {
            // Toggle between normal and maximized window state
            if (WindowState == WindowState.Normal)
                WindowState = WindowState.Maximized;
            else
                WindowState = WindowState.Normal;
        }

        //----------------------------------------------------------------------------//

        // Event handler for the Minimize button click event
        private void btnMinimize_Click(object sender, RoutedEventArgs e)
        {
            // Minimize the window
            WindowState = WindowState.Minimized;
        }

        // End: Button Close | Restore | Minimize

        //----------------------------------------------------------------------------//

        // Importing user32.dll for ReleaseCapture function
        [DllImport("user32.DLL", EntryPoint = "ReleaseCapture")]
        private extern static void ReleaseCapture();

        // Importing user32.dll for SendMessage function
        [DllImport("user32.DLL", EntryPoint = "SendMessage")]
        private extern static void SendMessage(System.IntPtr hWnd, int wMsg, int wParam, int lParam);

        //----------------------------------------------------------------------------//

        // Event handler for the MouseDown event on the border
        private void Border_MouseDown(object sender, MouseButtonEventArgs e)
        {
            // Check if the left mouse button was pressed
            if (e.ChangedButton == MouseButton.Left)
            {
                // Release the mouse capture
                ReleaseCapture();

                // Get the window handle
                IntPtr windowHandle = new WindowInteropHelper(this).Handle;

                // Send a message to move the window
                SendMessage(windowHandle, 0x112, 0xf012, 0);
            }
        }
    }
}

//__---____---____---____---____---____---____---__.ooo END OF FILE ooo.__---____---____---____---____---____---____---__\\
