// <auto-generated />
namespace WPFModernVerticalMenu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Alter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alter));
        
        string IMigrationMetadata.Id
        {
            get { return "202409111257207_Alter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
