using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MVA_Poe.Classes
{
    public class Attachment // Defines a public class named Attachment
    {
        // Specifies that this property is the primary key in the database
        [Key]
        // Specifies that the value is generated by the database on insert
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        // Property for the attachment ID
        public int Id { get; set; }

        // Property for the file name of the attachment
        public string FileName { get; set; }

        // Property for the file size of the attachment
        public double FileSize { get; set; }

        // Property for the file content of the attachment, stored as a byte array
        public byte[] FileContent { get; set; }

        // Foreign Key for Report
        // Property for the report ID, which is a foreign key
        public int reportID { get; set; }
    }
}

//__---____---____---____---____---____---____---__.ooo END OF FILE ooo.__---____---____---____---____---____---____---__\\