using MVA_Poe.Classes;
using MVA_Poe.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MVA_poe.Data;

namespace MVA_poe.Classes
{
    public class Event
    {
        // Specifies that this property is the primary key in the database
        [Key]
        // Specifies that the value is generated by the database on insert
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int EventID { get; set; }

        // Property for the event name
        [Required]
        [MaxLength(100)]
        public string EventName { get; set; }

        // Property for the event description
        [MaxLength(500)]
        public string EventDesc { get; set; }

        // Property for the event date
        [Required]
        public DateTime EventDate { get; set; }

        // Property for the event location
        [MaxLength(200)]
        public string EventLoc { get; set; }   
        public EventCategory EventCat { get; set; }

        // Default constructor
        public Event()
        {
        }
    }
}
//__---____---____---____---____---____---____---__.ooo END OF FILE ooo.__---____---____---____---____---____---____---__\\
