using MVA_Poe.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MVA_Poe.Classes
{
    public class Report
    { // Specifies that this property is the primary key in the database
        [Key]
        // Specifies that the value is generated by the database on insert
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]

        // Property for the report ID
        public int reportID { get; set; }

        // Property for the report name
        public string reportName { get; set; }

        // Property for the report description
        public string reportDesc { get; set; }

        // Property for the report date
        public DateTime reportDate { get; set; }

        // Property for the report location
        public string reportLoc { get; set; }

        // Property for the report category, which is of type ReportCategory
        public ReportCategory reportCat { get; set; }

        // Property for a collection of attachments, initialized to null
        public ICollection<Attachment> Attachments { get; set; } = null;

        // Foreign Key for User
        // Property for the user ID, which is a foreign key
        public int userId { get; set; }

        // Property for the user who reported, of type User
        public User reportedBy { get; set; }

        //----------------------------------------------------------------------------//
        // Default constructor

        public Report()
        {
        }
    }
}//__---____---____---____---____---____---____---__.ooo END OF FILE ooo.__---____---____---____---____---____---____---__\\
