using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MVA_Poe.Classes
{
    public class User // Defines a public class named User
    {
        // Specifies that this property is the primary key in the database
        [Key]
        // Specifies that the value is generated by the database on insert
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        // Auto-incrementing ID for the user
        public int UserId { get; set; }

        // Property for the username
        public string uName { get; set; }

        // Property for the password
        public string pWord { get; set; }

        // Property for the first name
        public string fName { get; set; }

        // Property for the last name
        public string lName { get; set; }

        // Property for the email address
        public string email { get; set; }

        // Property for the user ID (could be a national ID or similar)
        public string ID { get; set; }

        // Property for the address
        public string address { get; set; }

        // Property for the language preference
        public string langPref { get; set; }
    }
}

//__---____---____---____---____---____---____---__.ooo END OF FILE ooo.__---____---____---____-