using MVA_Poe.Classes;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace MVA_poe.Controls
{
    /// <summary>
    /// Interaction logic for ImagesView.xaml
    /// </summary>
    public partial class ImagesView : UserControl // Defines a partial class named ImagesView that inherits from UserControl
    {
        // Property: Images
        // Observable collection of BitmapImage objects
        public ObservableCollection<BitmapImage> Images { get; set; }

        // Property: Attachments
        // Observable collection of Attachment objects
        public ObservableCollection<Attachment> Attachments { get; set; }

        // Constructor for the ImagesView class
        public ImagesView()
        {
            // Initialize the component (generated by XAML)
            InitializeComponent();
            // Initialize the Images collection
            Images = new ObservableCollection<BitmapImage>();
            // Set the ItemsSource of the ImageList to the Images collection
            ImageList.ItemsSource = Images;
        }

        // Method: AddImage
        // Adds a BitmapImage to the Images collection
        public void AddImage(BitmapImage image)
        {
            // Add the image to the Images collection
            Images.Add(image);
            // Commented out code for setting the file size text
            // txtSize.Text = FileSize;
        }

        // Method: AddAttachment
        // Adds an Attachment to the Attachments collection
        public void AddAttachment(Attachment attachment)
        {
            // Add the attachment to the Attachments collection
            Attachments.Add(attachment);
        }
    }
}

//__---____---____---____---____---____---____---__.ooo END OF FILE ooo.__---____---____---____---____---____---____---__\\