using System;
using System.Windows;
using System.Windows.Controls;

namespace MVA_poe.Controls
{
    /// <summary>
    /// Interaction logic for MyTextBox.xaml
    /// </summary>
    public partial class MyTextBox : UserControl
    {
        // Constructor for the MyTextBox class
        public MyTextBox()
        {
            // Initialize the component (generated by XAML)
            InitializeComponent();
        }

        // Property: Hint
        // Gets or sets the hint text
        public string Hint
        {
            get { return (string)GetValue(HintProperty); }
            set { SetValue(HintProperty, value); }
        }

        // Using a DependencyProperty as the backing store for Hint. This enables animation, styling, binding, etc ...
        public static readonly DependencyProperty HintProperty =
        DependencyProperty.Register("Hint", typeof(string), typeof(MyTextBox));

        // Property: Caption
        // Gets or sets the caption text
        public string Caption
        {
            get { return (string)GetValue(CaptionProperty); }
            set { SetValue(CaptionProperty, value); }
        }

        // Using a DependencyProperty as the backing store for Caption. This enables animation, styling, binding, etc ...
        public static readonly DependencyProperty CaptionProperty =
        DependencyProperty.Register("Caption", typeof(string), typeof(MyTextBox));

        // Property: Text
        // Gets or sets the text
        public string Text
        {
            get { return (string)GetValue(TextProperty); }
            set { SetValue(TextProperty, value); }
        }

        // Event handler for the TextChanged event of the TextBox
        private void TextBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            // Update the Text property with the text from the TextBox
            Text = textBox.Text;
        }

        // Using a DependencyProperty as the backing store for Text. This enables animation, styling, binding, etc ...
        public static readonly DependencyProperty TextProperty =
                   DependencyProperty.Register("Text", typeof(string), typeof(MyTextBox), new PropertyMetadata(string.Empty));
    }
}

//__---____---____---____---____---____---____---__.ooo END OF FILE ooo.__---____---____---____---____---____---____---__\\