using MVA_Poe.Classes;
using MVA_Poe.Data;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace MVA_poe.Controls
{
    /// <summary>
    /// Interaction logic for ReportInfo.xaml
    /// </summary>
    public partial class ReportInfo : UserControl // Defines a partial class named ReportInfo that inherits from UserControl
    {
        // Declare a private variable of type Report
        Report report;

        // Constructor for the ReportInfo class
        public ReportInfo()
        {
            // Initialize the component (generated by XAML)
            InitializeComponent();
        }

        // Method: PopulateReportDisplay
        // Populates the report display with the given report data
        public void PopulateReportDisplay(Report report)
        {
            // Assign the report parameter to the class-level report variable
            this.report = report;

            // Set the report title text
            reportTitle.Text += "" + report.reportName;

            // Set the location text box text
            LocationTextBox.Text = report.reportLoc;

            // Set the date text box text
            DateTextBox.Text = report.reportDate.ToString("MM/dd/yyyy");

            // Set the category text box text
            CategoryTextBox.Text = GetCategory();

            // Set the description text box text
            DescriptionTextBox.Text = report.reportDesc;

            // Loop through each attachment in the report
            foreach (var attachment in report.Attachments)
            {
                // Check if the attachment is an image
                if (attachment.FileName.EndsWith(".png") || attachment.FileName.EndsWith(".jpeg") || attachment.FileName.EndsWith(".jpg"))
                {
                    // Convert byte array to BitmapImage
                    BitmapImage image = new BitmapImage();
                    using (MemoryStream ms = new MemoryStream(attachment.FileContent))
                    {
                        image.BeginInit();
                        image.StreamSource = ms;
                        image.CacheOption = BitmapCacheOption.OnLoad;
                        image.EndInit();
                    }

                    // Add the image to the ImageAttachmentList user control
                    var imageControl = new ImagesView();
                    imageControl.AddImage(image);

                    // Add the image control to the MediaAttachmentsListBox
                    MediaAttachmentsListBox.Items.Add(imageControl);
                }
                else
                {
                    // Display the file attachment
                    GetFileDisplay(attachment);
                }
            }
        }

        // Method: GetFileDisplay
        // Displays the file attachment based on its type
        private void GetFileDisplay(MVA_Poe.Classes.Attachment attachment)
        {
            // Declare a BitmapImage variable
            BitmapImage image = null;

            // Check the file type and set the corresponding image
            if (attachment.FileName.EndsWith(".docx"))
            {
                image = new BitmapImage(new Uri("/Resources/DOC.png", UriKind.Relative));
            }
            else if (attachment.FileName.EndsWith(".pdf"))
            {
                image = new BitmapImage(new Uri("/Resources/PDF.png", UriKind.Relative));
            }
            else if (attachment.FileName.EndsWith(".txt"))
            {
                image = new BitmapImage(new Uri("/Resources/TXT.png", UriKind.Relative));
            }
            else
            {
                image = new BitmapImage(new Uri("/Resources/RAW.png", UriKind.Relative));
            }

            // If an image is set, add it to the ImageAttachmentList user control
            if (image != null)
            {
                var imageControl = new ImagesView();
                imageControl.AddImage(image);

                // Add the image control to the MediaAttachmentsListBox
                MediaAttachmentsListBox.Items.Add(imageControl);
            }
        }

        // Method: GetCategory
        // Returns the category of the report as a string
        private string GetCategory()
        {
            // Convert the report category to a string and format it
            ReportCategory category = (ReportCategory)report.reportCat;
            string catItem = System.Text.RegularExpressions.Regex.Replace(category.ToString(), "(\\B[A-Z])", " $1");
            return catItem;
        }
    }
}

//__---____---____---____---____---____---____---__.ooo END OF FILE ooo.__---____---____---____---____---____---____---__\\